---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)

```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  rename(latitude = lat, longitude = long) %>%
  select(
    boro = neighbourhood_group, neighbourhood, rating, price, room_type,
    latitude, longitude) %>%
  filter(!is.na(rating))
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}

borough_choices = nyc_airbnb %>% distinct(boro) %>% pull()

selectInput(
  "borough_choice",
  h3("Borough Choice"),
  choices = borough_choices,
  selected = "Manhattan"
)

sliderInput(
  "price_range",
  h3("Price Range"),
  100, 1000,
  value = c(100, 400))


room_choices = nyc_airbnb %>% pull(room_type) %>% unique()

radioButtons(
  "room_choice",
  h3("Room Type"),
  choices = room_choices
)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) %>% 
  filter(neighbourhood_group == input[[borough_choice]],
         room_type == input[[room_choice]],
         price %in% input[[price_range]][1]:input[[price_range]][2]) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label, alpha = 0.5, 
          type = "scatter", mode = "markers")
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

# renderTest(
#  input[["price_range"]]
#)

#nyc_airbnb %>% 
 # mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  #plot_ly(
   # y = ~ price, x = ~neighbourhood, color = ~neighbourhood,
    #type = "box", colors = "viridis"
  #)
```

### Chart C

```{r}

# renderTest(
 # input[["room_choice"]]
#)


#nyc_airbnb %>% 
 # count(neighbourhood) %>% 
  #mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  #plot_ly(
   # x = ~neighbourhood, y = ~n, color = ~neighbourhood,
    #type = "bar", colors = "viridis"
 # )
```

